# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=200)),
                ('api_parms', models.CharField(max_length=200)),
                ('api_method', models.CharField(max_length=200)),
                ('api_add_date', models.DateTimeField(verbose_name='date api added')),
            ],
        ),
    ]
