# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=200)),
                ('api_parms', models.CharField(max_length=200, null=True)),
                ('api_method', models.CharField(max_length=200)),
                ('api_add_date', models.DateTimeField(null=True, verbose_name='date api added')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('add_project_name', models.DateTimeField(null=True, verbose_name='date project added')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Project'),
        ),
    ]
