# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='add_project_name',
            new_name='add_project_date',
        ),
    ]
